[profile.default]
remappings = ["src/=src/"]
src = "src"
out = "out"
libs = ["lib"]
solc_version = "0.8.26"

optimizer = true
# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
